export default function() {
  return [
    {
      amt_at_work: 6384,
      comments: "",
      commission: 7.00,
      initial_stop_price: 64.77,
      long_or_short: "short",
      post_date: "3/8/17 6:45am",
      price_bought: "",
      price_sold: 63.84,
      quantity: 100,
      reason_for_entry: "mean reversion setup above upper 50sma bollinger band ",
      reason_for_exit: "",
      r_mult: "",
      risk_amt: 77,
      risk_pct: "",
      stock_name: "DISH Network Corp",
      stock_symbol: "DISH",
      target_price: 62.05,
      trade_date: "3/8/17 6:45am",
      trade_close_date: "",
      trade_style: "mean reversion" // momentum or mean reversion
    },
    {
      amt_at_work: "",
      comments: "",
      commission: "",
      initial_stop_price: "",
      long_or_short: "",
      post_date: "",
      price_bought: "",
      price_sold: "",
      quantity: "",
      reason_for_entry: "",
      reason_for_exit: "",
      r_mult: "",
      risk_amt: "",
      risk_pct: "",
      stock_name: "",
      stock_symbol: "",
      target_price: "",
      trade_date: "",
      trade_close_date: "",
      trade_style: "" // momentum or mean reversion
    },
    {
      amt_at_work: "",
      comments: "",
      commission: "",
      initial_stop_price: "",
      long_or_short: "",
      post_date: "",
      price_bought: "",
      price_sold: "",
      quantity: "",
      reason_for_entry: "",
      reason_for_exit: "",
      r_mult: "",
      risk_amt: "",
      risk_pct: "",
      stock_name: "",
      stock_symbol: "",
      target_price: "",
      trade_date: "",
      trade_close_date: "",
      trade_style: "" // momentum or mean reversion
    }
  ];
}
